"use client";

import type { FC } from "react";
import { useMemo, useState } from "react";
import type { Persona } from "@/lib/personas/types";
import { Button } from "../ui/button";
import { PersonaDisplay } from "../ui/persona-display";

interface PersonaBrowserProps {
  personas: Persona[];
  projectedPersonasCount?: number | null;
}

const buildSearchString = (persona: Persona): string => {
  const name =
    `${persona.profileFirstName ?? ""} ${persona.profileLastName ?? ""}`.trim();
  const occupation = persona.profileOccupation ?? "";
  const city = persona.profileLocationCity ?? "";
  const state = persona.profileLocationState ?? "";
  return `${name} ${occupation} ${city} ${state}`.toLowerCase();
};

export const PersonaBrowser: FC<PersonaBrowserProps> = ({
  personas,
  projectedPersonasCount,
}) => {
  const [search, setSearch] = useState("");
  const [showAll, setShowAll] = useState(false);
  const [pagesViewed, setPagesViewed] = useState(1);

  const filtered = useMemo(() => {
    const query = search.trim().toLowerCase();
    if (!query) {
      return personas;
    }
    return personas.filter((persona) =>
      buildSearchString(persona).includes(query)
    );
  }, [personas, search]);

  const displayedPersonas = useMemo(() => {
    if (showAll || filtered.length <= 5) {
      return filtered;
    }
    return filtered.slice(0, 5 * pagesViewed);
  }, [filtered, showAll, pagesViewed]);

  const handleShowMore = () => {
    if (showAll) {
      return;
    }
    // If we've shown all available personas, set showAll to true
    if (displayedPersonas.length >= filtered.length) {
      setShowAll(true);
      return;
    }
    setPagesViewed((prev) => prev + 1);
  };

  if (personas.length === 0) {
    return null;
  }

  return (
    <section className="mt-8">
      <div className="mx-auto w-full max-w-5xl space-y-6">
        <div>
          <h2 className="font-medium text-lg">Your Simulated Audience</h2>
          <p className="text-muted-foreground text-sm">
            Click a persona tile to explore the detailed profile dialogue.
          </p>
        </div>

        <div className="flex items-center">
          <input
            className="w-full rounded-md border border-border bg-transparent px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
            onChange={(event) => setSearch(event.target.value)}
            placeholder={
              projectedPersonasCount
                ? `Search amongst ${projectedPersonasCount.toLocaleString()} personas generated by name, occupation, or location...`
                : "Search personas by name, occupation, or location..."
            }
            value={search}
          />
        </div>

        <div className="grid gap-4 lg:grid-cols-1">
          {displayedPersonas.map((persona) => (
            <PersonaDisplay key={persona.personaId} persona={persona} />
          ))}
        </div>

        {projectedPersonasCount && !showAll && (
          <div className="flex justify-center">
            <Button className="mt-4" onClick={handleShowMore} variant="outline">
              Show more ({projectedPersonasCount - 5 * pagesViewed} more
              personas)
            </Button>
          </div>
        )}
      </div>
    </section>
  );
};

export default PersonaBrowser;
